[env:atmega328p]
platform = atmelavr
board = nanoatmega328new
framework = arduino

; Serieller Monitor (über CH340C USB)
monitor_speed = 115200

; Einstellungen für ISP-Programmer (falls du initial die Fuses/Bootloader flasht)
; upload_protocol = usbasp ; Oder dein jeweiliger ISP-Programmer

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5